import path from 'node:path';
import { systemClock, type Clock } from '@worldview/world-model';
import { silentLogger, type Logger } from '@worldview/core';
import type { SidecarStatus } from './types.js';

/**
 * go2rtc sidecar manager (ADR-009). go2rtc is an optional, MIT-licensed binary that
 * WORLDVIEW does NOT bundle: the operator downloads the pinned release, verifies the
 * published checksum and configures its path (docs/operator/cameras.md,
 * docs/legal/SOFTWARE-LICENSES.md). FFmpeg is never downloaded or shipped by WORLDVIEW.
 *
 * The generated configuration binds every listener to 127.0.0.1 (API and RTSP) and
 * disables the WebRTC/SRTP listeners that would otherwise open 0.0.0.0 ports. The
 * admin UI is only reachable on loopback and is never exposed by the app. Streams are
 * added through the API at runtime, so camera credentials never touch the YAML file.
 */
export const GO2RTC_PINNED_VERSION = '1.9.14';
export const GO2RTC_API_PORT = 1984;
export const GO2RTC_RTSP_PORT = 8554;
export const GO2RTC_CONFIG_FILE = 'go2rtc.yaml';

export interface SpawnedProcess {
  pid?: number | undefined;
  kill(signal?: NodeJS.Signals | number): boolean;
  on(event: 'exit', listener: (code: number | null, signal: string | null) => void): unknown;
  on(event: 'error', listener: (err: Error) => void): unknown;
}

export type SpawnFn = (command: string, args: string[], opts: { cwd: string }) => SpawnedProcess;

/** Minimal fetch surface so tests can run without a binary or network. */
export type FetchLike = (
  url: string,
  init?: { method?: string; headers?: Record<string, string>; signal?: AbortSignal },
) => Promise<{
  status: number;
  headers: { get(name: string): string | null };
  json(): Promise<unknown>;
  arrayBuffer(): Promise<ArrayBuffer>;
}>;

export interface Go2rtcSidecarOptions {
  /** Absolute path to the go2rtc binary. Undefined = not configured; the sidecar never starts. */
  binaryPath?: string;
  /** Directory the generated config is written to (app data dir). */
  configDir: string;
  apiPort?: number;
  rtspPort?: number;
  spawn: SpawnFn;
  fetch: FetchLike;
  fileExists(filePath: string): boolean;
  writeFile(filePath: string, content: string): Promise<void>;
  logger?: Logger;
  clock?: Clock;
  sleep?: (ms: number) => Promise<void>;
  /** How long to wait for `GET /api` after spawning (default 8 s). */
  healthTimeoutMs?: number;
}

export class Go2rtcSidecar {
  private readonly logger: Logger;
  private readonly clock: Clock;
  private readonly apiPort: number;
  private readonly rtspPort: number;
  private process: SpawnedProcess | undefined;
  private state: SidecarStatus = { id: 'go2rtc', status: 'not-configured' };

  constructor(private readonly opts: Go2rtcSidecarOptions) {
    this.logger = opts.logger ?? silentLogger;
    this.clock = opts.clock ?? systemClock;
    this.apiPort = opts.apiPort ?? GO2RTC_API_PORT;
    this.rtspPort = opts.rtspPort ?? GO2RTC_RTSP_PORT;
    if (opts.binaryPath) this.state = { id: 'go2rtc', status: 'stopped' };
  }

  status(): SidecarStatus {
    return { ...this.state };
  }

  /**
   * Point the sidecar at a different binary (the operator changed the setting). A running
   * process is stopped first: the next `start()` uses the new path, so a path change can
   * never leave the previously configured binary running under the new label.
   */
  async setBinaryPath(binaryPath: string | undefined): Promise<void> {
    const next = binaryPath && binaryPath.length > 0 ? binaryPath : undefined;
    if (next === this.opts.binaryPath) return;
    await this.stop();
    if (next === undefined) delete this.opts.binaryPath;
    else this.opts.binaryPath = next;
    this.state = next ? { id: 'go2rtc', status: 'stopped' } : { id: 'go2rtc', status: 'not-configured' };
    this.logger.info('go2rtc binary path changed', { configured: next !== undefined });
  }
  isRunning(): boolean {
    return this.state.status === 'running';
  }
  configured(): boolean {
    return Boolean(this.opts.binaryPath);
  }
  apiBase(): string {
    return `http://127.0.0.1:${this.apiPort}`;
  }
  configPath(): string {
    return path.join(this.opts.configDir, GO2RTC_CONFIG_FILE);
  }

  /**
   * Loopback-only configuration. Every `listen` value is either a 127.0.0.1 address or
   * empty (listener disabled). Tests assert this invariant on the generated text.
   */
  generateConfig(): string {
    return [
      '# Generated by WorldView on every sidecar start. Do not edit; changes are overwritten.',
      `# Pinned go2rtc release: v${GO2RTC_PINNED_VERSION}. Streams are added through the loopback API, never written here.`,
      'api:',
      `  listen: "127.0.0.1:${this.apiPort}"`,
      'rtsp:',
      `  listen: "127.0.0.1:${this.rtspPort}"`,
      'webrtc:',
      '  listen: ""',
      '  candidates: []',
      'srtp:',
      '  listen: ""',
      'log:',
      '  level: "warn"',
      'streams: {}',
      '',
    ].join('\n');
  }

  /** Start the sidecar. Returns false (without spawning) when no usable binary is configured. */
  async start(): Promise<boolean> {
    if (this.process) return this.isRunning();
    const binary = this.opts.binaryPath;
    if (!binary) {
      this.state = { id: 'go2rtc', status: 'not-configured', message: 'go2rtc binary path not configured' };
      return false;
    }
    if (!this.opts.fileExists(binary)) {
      this.state = { id: 'go2rtc', status: 'not-configured', message: 'configured go2rtc binary not found' };
      this.logger.warn('go2rtc binary missing; sidecar not started', { binary });
      return false;
    }
    const config = this.configPath();
    await this.opts.writeFile(config, this.generateConfig());
    let proc: SpawnedProcess;
    try {
      proc = this.opts.spawn(binary, ['-config', config], { cwd: this.opts.configDir });
    } catch (err) {
      this.state = {
        id: 'go2rtc',
        status: 'error',
        message: `spawn failed: ${err instanceof Error ? err.message : String(err)}`,
      };
      return false;
    }
    this.process = proc;
    proc.on('error', (err) => {
      this.state = { id: 'go2rtc', status: 'error', message: err.message };
      this.process = undefined;
    });
    proc.on('exit', (code, signal) => {
      this.process = undefined;
      this.state =
        code === 0 || signal
          ? { id: 'go2rtc', status: 'stopped' }
          : { id: 'go2rtc', status: 'error', message: `go2rtc exited with code ${code ?? 'null'}` };
      this.logger.info('go2rtc exited', { code: code ?? null, signal: signal ?? null });
    });

    const deadline = this.clock.now() + (this.opts.healthTimeoutMs ?? 8000);
    const sleep = this.opts.sleep ?? ((ms: number) => new Promise<void>((r) => setTimeout(r, ms)));
    for (;;) {
      const h = await this.health();
      if (h.ok) {
        const version = h.version;
        const mismatch = version !== undefined && version !== GO2RTC_PINNED_VERSION;
        this.state = {
          id: 'go2rtc',
          status: 'running',
          ...(version ? { version } : {}),
          ...(mismatch ? { message: `running v${version}, pinned v${GO2RTC_PINNED_VERSION}` } : {}),
        };
        if (mismatch)
          this.logger.warn('go2rtc version differs from pinned release', {
            version: version ?? '',
            pinned: GO2RTC_PINNED_VERSION,
          });
        this.logger.info('go2rtc sidecar running', { apiPort: this.apiPort, rtspPort: this.rtspPort });
        return true;
      }
      if (!this.process || this.clock.now() >= deadline) break;
      await sleep(250);
    }
    if (this.process) {
      this.process.kill();
      this.process = undefined;
    }
    this.state = { id: 'go2rtc', status: 'error', message: 'go2rtc did not answer on the loopback API' };
    return false;
  }

  async health(): Promise<{ ok: boolean; version?: string }> {
    try {
      const res = await this.opts.fetch(`${this.apiBase()}/api`, { method: 'GET', signal: AbortSignal.timeout(1500) });
      if (res.status !== 200) return { ok: false };
      const body = (await res.json()) as { version?: unknown } | null;
      const version =
        body && typeof body === 'object' && typeof body.version === 'string'
          ? body.version.replace(/^v/, '')
          : undefined;
      return version ? { ok: true, version } : { ok: true };
    } catch {
      return { ok: false };
    }
  }

  async stop(): Promise<void> {
    const proc = this.process;
    if (proc) {
      proc.kill();
      this.process = undefined;
    }
    this.state = this.opts.binaryPath
      ? { id: 'go2rtc', status: 'stopped' }
      : { id: 'go2rtc', status: 'not-configured' };
  }

  async dispose(): Promise<void> {
    await this.stop();
  }
}
